### local - /
GET https://localhost:3000/ HTTP/1.1

### local - /setup
GET http://localhost:3002/setup HTTP/1.1
ApiKey: hunter2

### local - executa sorteio 
GET http://localhost:3002/sorteio HTTP/1.1
Content-Type: application/json
ApiKey: hunter2


### local - post
POST http://localhost:3002/books HTTP/1.1
Content-Type: application/json

ApiKey: hunter2

{
    "author": "J.K. Rowling",
    "title": "Harry Potter 4",
    "data": 
            [{
                "volume": 1,
                "pages": 104,
                "data_of_release": "2022-02-04"
            }]
}

### local - put
PUT http://localhost:3002/book/8 HTTP/1.1
Content-Type: application/json
ApiKey: hunter2

{
    "author": "J.K. Rowling",
    "title": "Harry Potter 8",
    "data": 
            [{
                "volume": 1,
                "pages": 108,
                "data_of_release": "2022-02-08"
            }]
}

### local - delete
DELETE http://localhost:3002/books/5
ApiKey: hunter2
Content-Type: application/json

### local - atualiza presenca da unidade
POST http://localhost:3000/atualiza_presenca HTTP/1.1
Content-Type: application/json
ApiKey: hunter2

{
    "unidade": "T1041",
    "presenca": "false"
}

### Heroku - get
GET https://sorteio-vagas-gli.herokuapp.com HTTP/1.1

### heroku - /setup
GET https://sorteio-vagas-gli.herokuapp.com/setup HTTP/1.1
ApiKey: tFe13jc8lzeKH9W6L5S^YwJWB&JmfJGa

### heroku - executa sorteio 
GET https://sorteio-vagas-gli.herokuapp.com/sorteio HTTP/1.1
Content-Type: application/json
ApiKey: tFe13jc8lzeKH9W6L5S^YwJWB&JmfJGa

### heroku - reinicia sorteio 
GET https://sorteio-vagas-gli.herokuapp.com/sorteio/recomecar HTTP/1.1
Content-Type: application/json
ApiKey: tFe13jc8lzeKH9W6L5S^YwJWB&JmfJGa

### Heroku local
GET https://localhost:3000/ HTTP/1.1
