-- CREATE ROLE api_user WITH LOGIN PASSWORD 'password';
-- ALTER ROLE api_user CREATEDB;

-- CREATE DATABASE sorteio_vagas;
-- \c sorteio_vagas

DROP TABLE IF EXISTS configuracao;
DROP TABLE IF EXISTS unidades;
DROP TABLE IF EXISTS vagas;

CREATE TABLE configuracao (
  id SERIAL PRIMARY KEY,
  ultimo_sorteio TIMESTAMP,
  resultado_sorteio VARCHAR(255)
);
INSERT INTO configuracao (ultimo_sorteio, resultado_sorteio) values (NOW(), 'Sorteio não realizado');

CREATE TABLE vagas (
  codigo CHAR(5) PRIMARY KEY,
  bloqueada BOOLEAN,
  ultima_gravacao TIMESTAMP default CURRENT_TIMESTAMP
);

CREATE TABLE unidades (
  unidade CHAR(5) PRIMARY KEY,
  pne BOOLEAN,
  presente BOOLEAN,
  adimplente BOOLEAN,
  vaga_sorteada CHAR(5) REFERENCES Vagas (codigo),
  user_id CHAR(80),
  ultima_gravacao TIMESTAMP default CURRENT_TIMESTAMP,
  vagas_escolhidas JSONB
);

INSERT INTO vagas (codigo, bloqueada) VALUES ('S1G01', false);
INSERT INTO vagas (codigo, bloqueada) VALUES ('S1G02', false);
INSERT INTO vagas (codigo, bloqueada) VALUES ('S1G03', false);
INSERT INTO vagas (codigo, bloqueada) VALUES ('S1G04', false);
INSERT INTO vagas (codigo, bloqueada) VALUES ('S1G05', false);
INSERT INTO vagas (codigo, bloqueada) VALUES ('S1G06', false);
INSERT INTO vagas (codigo, bloqueada) VALUES ('S1G07', false);
INSERT INTO vagas (codigo, bloqueada) VALUES ('S1G08', false);
INSERT INTO vagas (codigo, bloqueada) VALUES ('S1G09', false);
INSERT INTO vagas (codigo, bloqueada) VALUES ('S1G10', false);
INSERT INTO vagas (codigo, bloqueada) VALUES ('S1G11', false);
INSERT INTO vagas (codigo, bloqueada) VALUES ('S1G12', false);
INSERT INTO vagas (codigo, bloqueada) VALUES ('S1G13', false);
INSERT INTO vagas (codigo, bloqueada) VALUES ('S1G14', false);
INSERT INTO vagas (codigo, bloqueada) VALUES ('S1G15', false);
INSERT INTO vagas (codigo, bloqueada) VALUES ('S1G16', false);
INSERT INTO vagas (codigo, bloqueada) VALUES ('S1G17', false);
INSERT INTO vagas (codigo, bloqueada) VALUES ('S1G18', false);
INSERT INTO vagas (codigo, bloqueada) VALUES ('S1G19', false);
INSERT INTO vagas (codigo, bloqueada) VALUES ('S1G20', false);
INSERT INTO vagas (codigo, bloqueada) VALUES ('S1G21', false);
INSERT INTO vagas (codigo, bloqueada) VALUES ('S1G22', false);
INSERT INTO vagas (codigo, bloqueada) VALUES ('S1G23', false);
INSERT INTO vagas (codigo, bloqueada) VALUES ('S1G24', false);
INSERT INTO vagas (codigo, bloqueada) VALUES ('S1G25', false);
INSERT INTO vagas (codigo, bloqueada) VALUES ('S1G26', false);
INSERT INTO vagas (codigo, bloqueada) VALUES ('S1G27', false);
INSERT INTO vagas (codigo, bloqueada) VALUES ('S1G28', false);
INSERT INTO vagas (codigo, bloqueada) VALUES ('S1G29', false);
INSERT INTO vagas (codigo, bloqueada) VALUES ('S1G30', false);
INSERT INTO vagas (codigo, bloqueada) VALUES ('S1G31', false);
INSERT INTO vagas (codigo, bloqueada) VALUES ('S1G32', false);
INSERT INTO vagas (codigo, bloqueada) VALUES ('S1G33', false);
INSERT INTO vagas (codigo, bloqueada) VALUES ('S1G34', false);
INSERT INTO vagas (codigo, bloqueada) VALUES ('S1G35', false);
INSERT INTO vagas (codigo, bloqueada) VALUES ('S1G36', false);
INSERT INTO vagas (codigo, bloqueada) VALUES ('S1G37', false);
INSERT INTO vagas (codigo, bloqueada) VALUES ('S1G38', false);
INSERT INTO vagas (codigo, bloqueada) VALUES ('S1G39', false);
INSERT INTO vagas (codigo, bloqueada) VALUES ('S1G40', false);
INSERT INTO vagas (codigo, bloqueada) VALUES ('S1G41', false);
INSERT INTO vagas (codigo, bloqueada) VALUES ('S1G42', false);
INSERT INTO vagas (codigo, bloqueada) VALUES ('S1G43', false);
INSERT INTO vagas (codigo, bloqueada) VALUES ('S1G44', false);
INSERT INTO vagas (codigo, bloqueada) VALUES ('S1G45', false);
INSERT INTO vagas (codigo, bloqueada) VALUES ('S1G46', false);
INSERT INTO vagas (codigo, bloqueada) VALUES ('S1G47', false);
INSERT INTO vagas (codigo, bloqueada) VALUES ('S1G48', false);
INSERT INTO vagas (codigo, bloqueada) VALUES ('S1G49', false);
INSERT INTO vagas (codigo, bloqueada) VALUES ('S1G50', false);
INSERT INTO vagas (codigo, bloqueada) VALUES ('S1G51', false);
INSERT INTO vagas (codigo, bloqueada) VALUES ('S1G52', false);
INSERT INTO vagas (codigo, bloqueada) VALUES ('S1G53', false);
INSERT INTO vagas (codigo, bloqueada) VALUES ('S1G54', false);
INSERT INTO vagas (codigo, bloqueada) VALUES ('S1G55', false);
INSERT INTO vagas (codigo, bloqueada) VALUES ('S1G56', false);
INSERT INTO vagas (codigo, bloqueada) VALUES ('S1G57', false);
INSERT INTO vagas (codigo, bloqueada) VALUES ('S1G58', false);
INSERT INTO vagas (codigo, bloqueada) VALUES ('S1G59', false);
INSERT INTO vagas (codigo, bloqueada) VALUES ('S1G60', false);
INSERT INTO vagas (codigo, bloqueada) VALUES ('S1G61', false);
INSERT INTO vagas (codigo, bloqueada) VALUES ('S1G62', false);
INSERT INTO vagas (codigo, bloqueada) VALUES ('S1G63', false);
INSERT INTO vagas (codigo, bloqueada) VALUES ('S1G64', false);
INSERT INTO vagas (codigo, bloqueada) VALUES ('S1G65', false);
INSERT INTO vagas (codigo, bloqueada) VALUES ('S1G66', false);
INSERT INTO vagas (codigo, bloqueada) VALUES ('S1G67', false);
INSERT INTO vagas (codigo, bloqueada) VALUES ('S1G68', false);
INSERT INTO vagas (codigo, bloqueada) VALUES ('S1G69', false);
INSERT INTO vagas (codigo, bloqueada) VALUES ('S1G70', false);
INSERT INTO vagas (codigo, bloqueada) VALUES ('S1G71', false);
INSERT INTO vagas (codigo, bloqueada) VALUES ('S1G72', false);
INSERT INTO vagas (codigo, bloqueada) VALUES ('S1G73', false);
INSERT INTO vagas (codigo, bloqueada) VALUES ('S1G74', false);
INSERT INTO vagas (codigo, bloqueada) VALUES ('S1G75', false);
INSERT INTO vagas (codigo, bloqueada) VALUES ('S1G76', false);
INSERT INTO vagas (codigo, bloqueada) VALUES ('S1G77', false);
INSERT INTO vagas (codigo, bloqueada) VALUES ('S1G78', false);
INSERT INTO vagas (codigo, bloqueada) VALUES ('S1G79', false);
INSERT INTO vagas (codigo, bloqueada) VALUES ('S1G80', false);
INSERT INTO vagas (codigo, bloqueada) VALUES ('S1G81', false);
INSERT INTO vagas (codigo, bloqueada) VALUES ('S1G82', false);
INSERT INTO vagas (codigo, bloqueada) VALUES ('S1G83', false);
INSERT INTO vagas (codigo, bloqueada) VALUES ('S1G84', false);
INSERT INTO vagas (codigo, bloqueada) VALUES ('S1G85', false);
INSERT INTO vagas (codigo, bloqueada) VALUES ('S1G86', false);
INSERT INTO vagas (codigo, bloqueada) VALUES ('S1G87', false);
INSERT INTO vagas (codigo, bloqueada) VALUES ('S1G88', false);
INSERT INTO vagas (codigo, bloqueada) VALUES ('S1G89', false);
INSERT INTO vagas (codigo, bloqueada) VALUES ('S1G90', false);
INSERT INTO vagas (codigo, bloqueada) VALUES ('S1G91', false);
INSERT INTO vagas (codigo, bloqueada) VALUES ('S1G92', false);
INSERT INTO vagas (codigo, bloqueada) VALUES ('S1G93', false);
INSERT INTO vagas (codigo, bloqueada) VALUES ('S1G94', false);

INSERT INTO vagas (codigo, bloqueada) VALUES ('S2G01', false);
INSERT INTO vagas (codigo, bloqueada) VALUES ('S2G02', false);
INSERT INTO vagas (codigo, bloqueada) VALUES ('S2G03', false);
INSERT INTO vagas (codigo, bloqueada) VALUES ('S2G04', false);
INSERT INTO vagas (codigo, bloqueada) VALUES ('S2G05', false);
INSERT INTO vagas (codigo, bloqueada) VALUES ('S2G06', false);
INSERT INTO vagas (codigo, bloqueada) VALUES ('S2G07', false);
INSERT INTO vagas (codigo, bloqueada) VALUES ('S2G08', false);
INSERT INTO vagas (codigo, bloqueada) VALUES ('S2G09', false);
INSERT INTO vagas (codigo, bloqueada) VALUES ('S2G10', false);
INSERT INTO vagas (codigo, bloqueada) VALUES ('S2G11', false);
INSERT INTO vagas (codigo, bloqueada) VALUES ('S2G12', false);
INSERT INTO vagas (codigo, bloqueada) VALUES ('S2G13', false);
INSERT INTO vagas (codigo, bloqueada) VALUES ('S2G14', false);
INSERT INTO vagas (codigo, bloqueada) VALUES ('S2G15', false);
INSERT INTO vagas (codigo, bloqueada) VALUES ('S2G16', false);
INSERT INTO vagas (codigo, bloqueada) VALUES ('S2G17', false);
INSERT INTO vagas (codigo, bloqueada) VALUES ('S2G18', false);
INSERT INTO vagas (codigo, bloqueada) VALUES ('S2G19', false);
INSERT INTO vagas (codigo, bloqueada) VALUES ('S2G20', false);
INSERT INTO vagas (codigo, bloqueada) VALUES ('S2G21', false);
INSERT INTO vagas (codigo, bloqueada) VALUES ('S2G22', false);
INSERT INTO vagas (codigo, bloqueada) VALUES ('S2G23', false);
INSERT INTO vagas (codigo, bloqueada) VALUES ('S2G24', false);
INSERT INTO vagas (codigo, bloqueada) VALUES ('S2G25', false);
INSERT INTO vagas (codigo, bloqueada) VALUES ('S2G26', false);
INSERT INTO vagas (codigo, bloqueada) VALUES ('S2G27', false);
INSERT INTO vagas (codigo, bloqueada) VALUES ('S2G28', false);
INSERT INTO vagas (codigo, bloqueada) VALUES ('S2G29', false);
INSERT INTO vagas (codigo, bloqueada) VALUES ('S2G30', false);
INSERT INTO vagas (codigo, bloqueada) VALUES ('S2G31', false);
INSERT INTO vagas (codigo, bloqueada) VALUES ('S2G32', false);
INSERT INTO vagas (codigo, bloqueada) VALUES ('S2G33', false);
INSERT INTO vagas (codigo, bloqueada) VALUES ('S2G34', false);
INSERT INTO vagas (codigo, bloqueada) VALUES ('S2G35', false);
INSERT INTO vagas (codigo, bloqueada) VALUES ('S2G36', false);
INSERT INTO vagas (codigo, bloqueada) VALUES ('S2G37', false);
INSERT INTO vagas (codigo, bloqueada) VALUES ('S2G38', false);
INSERT INTO vagas (codigo, bloqueada) VALUES ('S2G39', false);
INSERT INTO vagas (codigo, bloqueada) VALUES ('S2G40', false);
INSERT INTO vagas (codigo, bloqueada) VALUES ('S2G41', false);
INSERT INTO vagas (codigo, bloqueada) VALUES ('S2G42', false);
INSERT INTO vagas (codigo, bloqueada) VALUES ('S2G43', false);
INSERT INTO vagas (codigo, bloqueada) VALUES ('S2G44', false);
INSERT INTO vagas (codigo, bloqueada) VALUES ('S2G45', false);
INSERT INTO vagas (codigo, bloqueada) VALUES ('S2G46', false);
INSERT INTO vagas (codigo, bloqueada) VALUES ('S2G47', false);
INSERT INTO vagas (codigo, bloqueada) VALUES ('S2G48', false);
INSERT INTO vagas (codigo, bloqueada) VALUES ('S2G49', false);
INSERT INTO vagas (codigo, bloqueada) VALUES ('S2G50', false);
INSERT INTO vagas (codigo, bloqueada) VALUES ('S2G51', false);
INSERT INTO vagas (codigo, bloqueada) VALUES ('S2G52', false);
INSERT INTO vagas (codigo, bloqueada) VALUES ('S2G53', false);
INSERT INTO vagas (codigo, bloqueada) VALUES ('S2G54', false);
INSERT INTO vagas (codigo, bloqueada) VALUES ('S2G55', false);
INSERT INTO vagas (codigo, bloqueada) VALUES ('S2G56', false);
INSERT INTO vagas (codigo, bloqueada) VALUES ('S2G57', false);
INSERT INTO vagas (codigo, bloqueada) VALUES ('S2G58', false);
INSERT INTO vagas (codigo, bloqueada) VALUES ('S2G59', false);
INSERT INTO vagas (codigo, bloqueada) VALUES ('S2G60', false);
INSERT INTO vagas (codigo, bloqueada) VALUES ('S2G61', false);
INSERT INTO vagas (codigo, bloqueada) VALUES ('S2G62', false);
INSERT INTO vagas (codigo, bloqueada) VALUES ('S2G63', false);
INSERT INTO vagas (codigo, bloqueada) VALUES ('S2G64', false);
INSERT INTO vagas (codigo, bloqueada) VALUES ('S2G65', false);
INSERT INTO vagas (codigo, bloqueada) VALUES ('S2G66', false);
INSERT INTO vagas (codigo, bloqueada) VALUES ('S2G67', false);
INSERT INTO vagas (codigo, bloqueada) VALUES ('S2G68', false);
INSERT INTO vagas (codigo, bloqueada) VALUES ('S2G69', false);
INSERT INTO vagas (codigo, bloqueada) VALUES ('S2G70', false);
INSERT INTO vagas (codigo, bloqueada) VALUES ('S2G71', false);
INSERT INTO vagas (codigo, bloqueada) VALUES ('S2G72', false);
INSERT INTO vagas (codigo, bloqueada) VALUES ('S2G73', false);
INSERT INTO vagas (codigo, bloqueada) VALUES ('S2G74', false);
INSERT INTO vagas (codigo, bloqueada) VALUES ('S2G75', false);
INSERT INTO vagas (codigo, bloqueada) VALUES ('S2G76', false);
INSERT INTO vagas (codigo, bloqueada) VALUES ('S2G77', false);
INSERT INTO vagas (codigo, bloqueada) VALUES ('S2G78', false);
INSERT INTO vagas (codigo, bloqueada) VALUES ('S2G79', false);
INSERT INTO vagas (codigo, bloqueada) VALUES ('S2G80', false);
INSERT INTO vagas (codigo, bloqueada) VALUES ('S2G81', false);
INSERT INTO vagas (codigo, bloqueada) VALUES ('S2G82', false);
INSERT INTO vagas (codigo, bloqueada) VALUES ('S2G83', false);
INSERT INTO vagas (codigo, bloqueada) VALUES ('S2G84', false);
INSERT INTO vagas (codigo, bloqueada) VALUES ('S2G85', false);
INSERT INTO vagas (codigo, bloqueada) VALUES ('S2G86', false);
INSERT INTO vagas (codigo, bloqueada) VALUES ('S2G87', false);
INSERT INTO vagas (codigo, bloqueada) VALUES ('S2G88', false);
INSERT INTO vagas (codigo, bloqueada) VALUES ('S2G89', false);
INSERT INTO vagas (codigo, bloqueada) VALUES ('S2G90', false);
INSERT INTO vagas (codigo, bloqueada) VALUES ('S2G91', false);
INSERT INTO vagas (codigo, bloqueada) VALUES ('S2G92', false);
INSERT INTO vagas (codigo, bloqueada) VALUES ('S2G93', false);
INSERT INTO vagas (codigo, bloqueada) VALUES ('S2G94', false);
INSERT INTO vagas (codigo, bloqueada) VALUES ('S2G95', false);
INSERT INTO vagas (codigo, bloqueada) VALUES ('S2G96', false);
INSERT INTO vagas (codigo, bloqueada) VALUES ('S2G97', false);
INSERT INTO vagas (codigo, bloqueada) VALUES ('S2G98', false);

INSERT INTO unidades (unidade, pne, presente, adimplente, vaga_sorteada, vagas_escolhidas) VALUES ('T1011', false, true, true, NULL, NULL);
INSERT INTO unidades (unidade, pne, presente, adimplente, vaga_sorteada, vagas_escolhidas) VALUES ('T1012', false, true, true, NULL, NULL);
INSERT INTO unidades (unidade, pne, presente, adimplente, vaga_sorteada, vagas_escolhidas) VALUES ('T1013', false, true, true, NULL, NULL);
INSERT INTO unidades (unidade, pne, presente, adimplente, vaga_sorteada, vagas_escolhidas) VALUES ('T1014', false, true, true, NULL, NULL);
INSERT INTO unidades (unidade, pne, presente, adimplente, vaga_sorteada, vagas_escolhidas) VALUES ('T1021', false, true, true, NULL, NULL);
INSERT INTO unidades (unidade, pne, presente, adimplente, vaga_sorteada, vagas_escolhidas) VALUES ('T1022', false, true, true, NULL, NULL);
INSERT INTO unidades (unidade, pne, presente, adimplente, vaga_sorteada, vagas_escolhidas) VALUES ('T1023', false, true, true, NULL, NULL);
INSERT INTO unidades (unidade, pne, presente, adimplente, vaga_sorteada, vagas_escolhidas) VALUES ('T1024', false, true, true, NULL, NULL);
INSERT INTO unidades (unidade, pne, presente, adimplente, vaga_sorteada, vagas_escolhidas) VALUES ('T1031', false, true, true, NULL, NULL);
INSERT INTO unidades (unidade, pne, presente, adimplente, vaga_sorteada, vagas_escolhidas) VALUES ('T1032', false, true, true, NULL, NULL);
INSERT INTO unidades (unidade, pne, presente, adimplente, vaga_sorteada, vagas_escolhidas) VALUES ('T1033', false, true, true, NULL, NULL);
INSERT INTO unidades (unidade, pne, presente, adimplente, vaga_sorteada, vagas_escolhidas) VALUES ('T1034', false, true, true, NULL, NULL);
INSERT INTO unidades (unidade, pne, presente, adimplente, vaga_sorteada, vagas_escolhidas) VALUES ('T1041', false, true, true, NULL, '[{"vaga": "S1G01"},{"vaga": "S1G02"}]');
INSERT INTO unidades (unidade, pne, presente, adimplente, vaga_sorteada, vagas_escolhidas) VALUES ('T1042', false, true, true, NULL, NULL);
INSERT INTO unidades (unidade, pne, presente, adimplente, vaga_sorteada, vagas_escolhidas) VALUES ('T1043', false, true, false, NULL, '[{"vaga": "S1G01"},{"vaga": "S1G03"}]');
INSERT INTO unidades (unidade, pne, presente, adimplente, vaga_sorteada, vagas_escolhidas) VALUES ('T1044', false, true, true, NULL, '[{"vaga": "S1G04"},{"vaga": "S1G05"}]');
INSERT INTO unidades (unidade, pne, presente, adimplente, vaga_sorteada, vagas_escolhidas) VALUES ('T1051', false, false, true, NULL, '[{"vaga": "S1G04"},{"vaga": "S1G05"}]');
INSERT INTO unidades (unidade, pne, presente, adimplente, vaga_sorteada, vagas_escolhidas) VALUES ('T1052', false, false, true, NULL, '[{"vaga": "S1G03"},{"vaga": "S1G04"},{"vaga": "S1G05"}]');
INSERT INTO unidades (unidade, pne, presente, adimplente, vaga_sorteada, vagas_escolhidas) VALUES ('T1053', true, true, true, NULL, '[{"vaga": "S1G01"},{"vaga": "S1G08"},{"vaga": "S1G04"}]');
INSERT INTO unidades (unidade, pne, presente, adimplente, vaga_sorteada, vagas_escolhidas) VALUES ('T1054', true, true, true, NULL, '[{"vaga": "S1G01"},{"vaga": "S1G08"},{"vaga": "S1G04"}]');
INSERT INTO unidades (unidade, pne, presente, adimplente, vaga_sorteada, vagas_escolhidas) VALUES ('T1061', true, true, true, NULL, NULL);
INSERT INTO unidades (unidade, pne, presente, adimplente, vaga_sorteada, vagas_escolhidas) VALUES ('T1062', false, true, true, NULL, NULL);
INSERT INTO unidades (unidade, pne, presente, adimplente, vaga_sorteada, vagas_escolhidas) VALUES ('T1063', false, true, true, NULL, NULL);
INSERT INTO unidades (unidade, pne, presente, adimplente, vaga_sorteada, vagas_escolhidas) VALUES ('T1064', false, true, true, NULL, NULL);
INSERT INTO unidades (unidade, pne, presente, adimplente, vaga_sorteada, vagas_escolhidas) VALUES ('T1071', false, true, true, NULL, NULL);
INSERT INTO unidades (unidade, pne, presente, adimplente, vaga_sorteada, vagas_escolhidas) VALUES ('T1072', false, true, true, NULL, NULL);
INSERT INTO unidades (unidade, pne, presente, adimplente, vaga_sorteada, vagas_escolhidas) VALUES ('T1073', false, true, true, NULL, NULL);
INSERT INTO unidades (unidade, pne, presente, adimplente, vaga_sorteada, vagas_escolhidas) VALUES ('T1074', false, true, true, NULL, NULL);
INSERT INTO unidades (unidade, pne, presente, adimplente, vaga_sorteada, vagas_escolhidas) VALUES ('T1081', false, true, true, NULL, NULL);
INSERT INTO unidades (unidade, pne, presente, adimplente, vaga_sorteada, vagas_escolhidas) VALUES ('T1082', false, true, true, NULL, NULL);
INSERT INTO unidades (unidade, pne, presente, adimplente, vaga_sorteada, vagas_escolhidas) VALUES ('T1083', false, true, true, NULL, NULL);
INSERT INTO unidades (unidade, pne, presente, adimplente, vaga_sorteada, vagas_escolhidas) VALUES ('T1084', false, true, true, NULL, NULL);
INSERT INTO unidades (unidade, pne, presente, adimplente, vaga_sorteada, vagas_escolhidas) VALUES ('T1091', false, true, true, NULL, NULL);
INSERT INTO unidades (unidade, pne, presente, adimplente, vaga_sorteada, vagas_escolhidas) VALUES ('T1092', false, true, true, NULL, NULL);
INSERT INTO unidades (unidade, pne, presente, adimplente, vaga_sorteada, vagas_escolhidas) VALUES ('T1093', false, true, true, NULL, NULL);
INSERT INTO unidades (unidade, pne, presente, adimplente, vaga_sorteada, vagas_escolhidas) VALUES ('T1094', false, true, true, NULL, NULL);
INSERT INTO unidades (unidade, pne, presente, adimplente, vaga_sorteada, vagas_escolhidas) VALUES ('T1101', false, true, true, NULL, NULL);
INSERT INTO unidades (unidade, pne, presente, adimplente, vaga_sorteada, vagas_escolhidas) VALUES ('T1102', false, true, true, NULL, NULL);
INSERT INTO unidades (unidade, pne, presente, adimplente, vaga_sorteada, vagas_escolhidas) VALUES ('T1103', false, true, true, NULL, NULL);
INSERT INTO unidades (unidade, pne, presente, adimplente, vaga_sorteada, vagas_escolhidas) VALUES ('T1104', false, true, true, NULL, NULL);
INSERT INTO unidades (unidade, pne, presente, adimplente, vaga_sorteada, vagas_escolhidas) VALUES ('T1111', false, true, true, NULL, NULL);
INSERT INTO unidades (unidade, pne, presente, adimplente, vaga_sorteada, vagas_escolhidas) VALUES ('T1112', false, true, true, NULL, NULL);
INSERT INTO unidades (unidade, pne, presente, adimplente, vaga_sorteada, vagas_escolhidas) VALUES ('T1113', false, true, true, NULL, NULL);
INSERT INTO unidades (unidade, pne, presente, adimplente, vaga_sorteada, vagas_escolhidas) VALUES ('T1114', false, true, true, NULL, NULL);
INSERT INTO unidades (unidade, pne, presente, adimplente, vaga_sorteada, vagas_escolhidas) VALUES ('T1121', false, true, true, NULL, NULL);
INSERT INTO unidades (unidade, pne, presente, adimplente, vaga_sorteada, vagas_escolhidas) VALUES ('T1122', false, true, true, NULL, NULL);
INSERT INTO unidades (unidade, pne, presente, adimplente, vaga_sorteada, vagas_escolhidas) VALUES ('T1123', false, true, true, NULL, NULL);
INSERT INTO unidades (unidade, pne, presente, adimplente, vaga_sorteada, vagas_escolhidas) VALUES ('T1124', false, true, true, NULL, NULL);
INSERT INTO unidades (unidade, pne, presente, adimplente, vaga_sorteada, vagas_escolhidas) VALUES ('T1131', false, true, true, NULL, NULL);
INSERT INTO unidades (unidade, pne, presente, adimplente, vaga_sorteada, vagas_escolhidas) VALUES ('T1132', false, true, true, NULL, NULL);
INSERT INTO unidades (unidade, pne, presente, adimplente, vaga_sorteada, vagas_escolhidas) VALUES ('T1133', false, true, true, NULL, NULL);
INSERT INTO unidades (unidade, pne, presente, adimplente, vaga_sorteada, vagas_escolhidas) VALUES ('T1134', false, true, true, NULL, NULL);
INSERT INTO unidades (unidade, pne, presente, adimplente, vaga_sorteada, vagas_escolhidas) VALUES ('T1141', false, true, true, NULL, NULL);
INSERT INTO unidades (unidade, pne, presente, adimplente, vaga_sorteada, vagas_escolhidas) VALUES ('T1142', false, true, true, NULL, NULL);
INSERT INTO unidades (unidade, pne, presente, adimplente, vaga_sorteada, vagas_escolhidas) VALUES ('T1143', false, true, true, NULL, NULL);
INSERT INTO unidades (unidade, pne, presente, adimplente, vaga_sorteada, vagas_escolhidas) VALUES ('T1144', false, true, true, NULL, NULL);
INSERT INTO unidades (unidade, pne, presente, adimplente, vaga_sorteada, vagas_escolhidas) VALUES ('T1151', false, true, true, NULL, NULL);
INSERT INTO unidades (unidade, pne, presente, adimplente, vaga_sorteada, vagas_escolhidas) VALUES ('T1152', false, true, true, NULL, NULL);
INSERT INTO unidades (unidade, pne, presente, adimplente, vaga_sorteada, vagas_escolhidas) VALUES ('T1153', false, true, true, NULL, NULL);
INSERT INTO unidades (unidade, pne, presente, adimplente, vaga_sorteada, vagas_escolhidas) VALUES ('T1154', false, true, true, NULL, NULL);
INSERT INTO unidades (unidade, pne, presente, adimplente, vaga_sorteada, vagas_escolhidas) VALUES ('T1161', false, true, true, NULL, NULL);
INSERT INTO unidades (unidade, pne, presente, adimplente, vaga_sorteada, vagas_escolhidas) VALUES ('T1162', false, true, true, NULL, NULL);
INSERT INTO unidades (unidade, pne, presente, adimplente, vaga_sorteada, vagas_escolhidas) VALUES ('T1163', false, true, true, NULL, NULL);
INSERT INTO unidades (unidade, pne, presente, adimplente, vaga_sorteada, vagas_escolhidas) VALUES ('T1164', false, true, true, NULL, NULL);
INSERT INTO unidades (unidade, pne, presente, adimplente, vaga_sorteada, vagas_escolhidas) VALUES ('T1171', false, true, true, NULL, NULL);
INSERT INTO unidades (unidade, pne, presente, adimplente, vaga_sorteada, vagas_escolhidas) VALUES ('T1172', false, true, true, NULL, NULL);
INSERT INTO unidades (unidade, pne, presente, adimplente, vaga_sorteada, vagas_escolhidas) VALUES ('T1173', false, true, true, NULL, NULL);
INSERT INTO unidades (unidade, pne, presente, adimplente, vaga_sorteada, vagas_escolhidas) VALUES ('T1174', false, true, true, NULL, NULL);
INSERT INTO unidades (unidade, pne, presente, adimplente, vaga_sorteada, vagas_escolhidas) VALUES ('T1181', false, true, true, NULL, NULL);
INSERT INTO unidades (unidade, pne, presente, adimplente, vaga_sorteada, vagas_escolhidas) VALUES ('T1182', false, true, true, NULL, NULL);
INSERT INTO unidades (unidade, pne, presente, adimplente, vaga_sorteada, vagas_escolhidas) VALUES ('T1183', false, true, true, NULL, NULL);
INSERT INTO unidades (unidade, pne, presente, adimplente, vaga_sorteada, vagas_escolhidas) VALUES ('T1184', false, true, true, NULL, NULL);
INSERT INTO unidades (unidade, pne, presente, adimplente, vaga_sorteada, vagas_escolhidas) VALUES ('T1191', false, true, true, NULL, NULL);
INSERT INTO unidades (unidade, pne, presente, adimplente, vaga_sorteada, vagas_escolhidas) VALUES ('T1192', false, true, true, NULL, NULL);
INSERT INTO unidades (unidade, pne, presente, adimplente, vaga_sorteada, vagas_escolhidas) VALUES ('T1193', false, true, true, NULL, NULL);
INSERT INTO unidades (unidade, pne, presente, adimplente, vaga_sorteada, vagas_escolhidas) VALUES ('T1194', false, true, true, NULL, NULL);
INSERT INTO unidades (unidade, pne, presente, adimplente, vaga_sorteada, vagas_escolhidas) VALUES ('T1201', false, true, true, NULL, NULL);
INSERT INTO unidades (unidade, pne, presente, adimplente, vaga_sorteada, vagas_escolhidas) VALUES ('T1202', false, true, true, NULL, NULL);
INSERT INTO unidades (unidade, pne, presente, adimplente, vaga_sorteada, vagas_escolhidas) VALUES ('T1203', false, true, true, NULL, NULL);
INSERT INTO unidades (unidade, pne, presente, adimplente, vaga_sorteada, vagas_escolhidas) VALUES ('T1204', false, true, true, NULL, NULL);
INSERT INTO unidades (unidade, pne, presente, adimplente, vaga_sorteada, vagas_escolhidas) VALUES ('T1211', false, true, true, NULL, NULL);
INSERT INTO unidades (unidade, pne, presente, adimplente, vaga_sorteada, vagas_escolhidas) VALUES ('T1212', false, true, true, NULL, NULL);
INSERT INTO unidades (unidade, pne, presente, adimplente, vaga_sorteada, vagas_escolhidas) VALUES ('T1213', false, true, true, NULL, NULL);
INSERT INTO unidades (unidade, pne, presente, adimplente, vaga_sorteada, vagas_escolhidas) VALUES ('T1214', false, true, true, NULL, NULL);
INSERT INTO unidades (unidade, pne, presente, adimplente, vaga_sorteada, vagas_escolhidas) VALUES ('T1221', false, true, true, NULL, NULL);
INSERT INTO unidades (unidade, pne, presente, adimplente, vaga_sorteada, vagas_escolhidas) VALUES ('T1222', false, true, true, NULL, NULL);
INSERT INTO unidades (unidade, pne, presente, adimplente, vaga_sorteada, vagas_escolhidas) VALUES ('T1223', false, true, true, NULL, NULL);
INSERT INTO unidades (unidade, pne, presente, adimplente, vaga_sorteada, vagas_escolhidas) VALUES ('T1224', false, true, true, NULL, NULL);
INSERT INTO unidades (unidade, pne, presente, adimplente, vaga_sorteada, vagas_escolhidas) VALUES ('T1231', false, true, true, NULL, NULL);
INSERT INTO unidades (unidade, pne, presente, adimplente, vaga_sorteada, vagas_escolhidas) VALUES ('T1232', false, true, true, NULL, NULL);
INSERT INTO unidades (unidade, pne, presente, adimplente, vaga_sorteada, vagas_escolhidas) VALUES ('T1233', false, true, true, NULL, NULL);
INSERT INTO unidades (unidade, pne, presente, adimplente, vaga_sorteada, vagas_escolhidas) VALUES ('T1234', false, true, true, NULL, NULL);
INSERT INTO unidades (unidade, pne, presente, adimplente, vaga_sorteada, vagas_escolhidas) VALUES ('T1241', false, true, true, NULL, NULL);
INSERT INTO unidades (unidade, pne, presente, adimplente, vaga_sorteada, vagas_escolhidas) VALUES ('T1242', false, true, true, NULL, NULL);
INSERT INTO unidades (unidade, pne, presente, adimplente, vaga_sorteada, vagas_escolhidas) VALUES ('T1243', false, true, true, NULL, NULL);
INSERT INTO unidades (unidade, pne, presente, adimplente, vaga_sorteada, vagas_escolhidas) VALUES ('T1244', false, true, true, NULL, NULL);

INSERT INTO unidades (unidade, pne, presente, adimplente, vaga_sorteada, vagas_escolhidas) VALUES ('T2011', false, true, true, NULL, NULL);
INSERT INTO unidades (unidade, pne, presente, adimplente, vaga_sorteada, vagas_escolhidas) VALUES ('T2012', false, true, true, NULL, NULL);
INSERT INTO unidades (unidade, pne, presente, adimplente, vaga_sorteada, vagas_escolhidas) VALUES ('T2013', false, true, true, NULL, NULL);
INSERT INTO unidades (unidade, pne, presente, adimplente, vaga_sorteada, vagas_escolhidas) VALUES ('T2014', false, true, true, NULL, NULL);
INSERT INTO unidades (unidade, pne, presente, adimplente, vaga_sorteada, vagas_escolhidas) VALUES ('T2021', false, true, true, NULL, NULL);
INSERT INTO unidades (unidade, pne, presente, adimplente, vaga_sorteada, vagas_escolhidas) VALUES ('T2022', false, true, true, NULL, NULL);
INSERT INTO unidades (unidade, pne, presente, adimplente, vaga_sorteada, vagas_escolhidas) VALUES ('T2023', false, true, true, NULL, NULL);
INSERT INTO unidades (unidade, pne, presente, adimplente, vaga_sorteada, vagas_escolhidas) VALUES ('T2024', false, true, true, NULL, NULL);
INSERT INTO unidades (unidade, pne, presente, adimplente, vaga_sorteada, vagas_escolhidas) VALUES ('T2031', false, true, true, NULL, NULL);
INSERT INTO unidades (unidade, pne, presente, adimplente, vaga_sorteada, vagas_escolhidas) VALUES ('T2032', false, true, true, NULL, NULL);
INSERT INTO unidades (unidade, pne, presente, adimplente, vaga_sorteada, vagas_escolhidas) VALUES ('T2033', false, true, true, NULL, NULL);
INSERT INTO unidades (unidade, pne, presente, adimplente, vaga_sorteada, vagas_escolhidas) VALUES ('T2034', false, true, true, NULL, NULL);
INSERT INTO unidades (unidade, pne, presente, adimplente, vaga_sorteada, vagas_escolhidas) VALUES ('T2041', false, true, true, NULL, '[{"vaga": "S1G01"},{"vaga": "S1G02"}]');
INSERT INTO unidades (unidade, pne, presente, adimplente, vaga_sorteada, vagas_escolhidas) VALUES ('T2042', false, true, true, NULL, NULL);
INSERT INTO unidades (unidade, pne, presente, adimplente, vaga_sorteada, vagas_escolhidas) VALUES ('T2043', false, true, false, NULL, '[{"vaga": "S1G01"},{"vaga": "S1G03"}]');
INSERT INTO unidades (unidade, pne, presente, adimplente, vaga_sorteada, vagas_escolhidas) VALUES ('T2044', false, true, true, NULL, '[{"vaga": "S1G04"},{"vaga": "S1G05"}]');
INSERT INTO unidades (unidade, pne, presente, adimplente, vaga_sorteada, vagas_escolhidas) VALUES ('T2051', false, false, true, NULL, '[{"vaga": "S1G04"},{"vaga": "S1G05"}]');
INSERT INTO unidades (unidade, pne, presente, adimplente, vaga_sorteada, vagas_escolhidas) VALUES ('T2052', false, false, true, NULL, '[{"vaga": "S1G03"},{"vaga": "S1G04"},{"vaga": "S1G05"}]');
INSERT INTO unidades (unidade, pne, presente, adimplente, vaga_sorteada, vagas_escolhidas) VALUES ('T2053', true, true, true, NULL, '[{"vaga": "S1G01"},{"vaga": "S1G08"},{"vaga": "S1G04"}]');
INSERT INTO unidades (unidade, pne, presente, adimplente, vaga_sorteada, vagas_escolhidas) VALUES ('T2054', true, true, true, NULL, '[{"vaga": "S1G01"},{"vaga": "S1G08"},{"vaga": "S1G04"}]');
INSERT INTO unidades (unidade, pne, presente, adimplente, vaga_sorteada, vagas_escolhidas) VALUES ('T2061', true, true, true, NULL, NULL);
INSERT INTO unidades (unidade, pne, presente, adimplente, vaga_sorteada, vagas_escolhidas) VALUES ('T2062', false, true, true, NULL, NULL);
INSERT INTO unidades (unidade, pne, presente, adimplente, vaga_sorteada, vagas_escolhidas) VALUES ('T2063', false, true, true, NULL, NULL);
INSERT INTO unidades (unidade, pne, presente, adimplente, vaga_sorteada, vagas_escolhidas) VALUES ('T2064', false, true, true, NULL, NULL);
INSERT INTO unidades (unidade, pne, presente, adimplente, vaga_sorteada, vagas_escolhidas) VALUES ('T2071', false, true, true, NULL, NULL);
INSERT INTO unidades (unidade, pne, presente, adimplente, vaga_sorteada, vagas_escolhidas) VALUES ('T2072', false, true, true, NULL, NULL);
INSERT INTO unidades (unidade, pne, presente, adimplente, vaga_sorteada, vagas_escolhidas) VALUES ('T2073', false, true, true, NULL, NULL);
INSERT INTO unidades (unidade, pne, presente, adimplente, vaga_sorteada, vagas_escolhidas) VALUES ('T2074', false, true, true, NULL, NULL);
INSERT INTO unidades (unidade, pne, presente, adimplente, vaga_sorteada, vagas_escolhidas) VALUES ('T2081', false, true, true, NULL, NULL);
INSERT INTO unidades (unidade, pne, presente, adimplente, vaga_sorteada, vagas_escolhidas) VALUES ('T2082', false, true, true, NULL, NULL);
INSERT INTO unidades (unidade, pne, presente, adimplente, vaga_sorteada, vagas_escolhidas) VALUES ('T2083', false, true, true, NULL, NULL);
INSERT INTO unidades (unidade, pne, presente, adimplente, vaga_sorteada, vagas_escolhidas) VALUES ('T2084', false, true, true, NULL, NULL);
INSERT INTO unidades (unidade, pne, presente, adimplente, vaga_sorteada, vagas_escolhidas) VALUES ('T2091', false, true, true, NULL, NULL);
INSERT INTO unidades (unidade, pne, presente, adimplente, vaga_sorteada, vagas_escolhidas) VALUES ('T2092', false, true, true, NULL, NULL);
INSERT INTO unidades (unidade, pne, presente, adimplente, vaga_sorteada, vagas_escolhidas) VALUES ('T2093', false, true, true, NULL, NULL);
INSERT INTO unidades (unidade, pne, presente, adimplente, vaga_sorteada, vagas_escolhidas) VALUES ('T2094', false, true, true, NULL, NULL);
INSERT INTO unidades (unidade, pne, presente, adimplente, vaga_sorteada, vagas_escolhidas) VALUES ('T2101', false, true, true, NULL, NULL);
INSERT INTO unidades (unidade, pne, presente, adimplente, vaga_sorteada, vagas_escolhidas) VALUES ('T2102', false, true, true, NULL, NULL);
INSERT INTO unidades (unidade, pne, presente, adimplente, vaga_sorteada, vagas_escolhidas) VALUES ('T2103', false, true, true, NULL, NULL);
INSERT INTO unidades (unidade, pne, presente, adimplente, vaga_sorteada, vagas_escolhidas) VALUES ('T2104', false, true, true, NULL, NULL);
INSERT INTO unidades (unidade, pne, presente, adimplente, vaga_sorteada, vagas_escolhidas) VALUES ('T2111', false, true, true, NULL, NULL);
INSERT INTO unidades (unidade, pne, presente, adimplente, vaga_sorteada, vagas_escolhidas) VALUES ('T2112', false, true, true, NULL, NULL);
INSERT INTO unidades (unidade, pne, presente, adimplente, vaga_sorteada, vagas_escolhidas) VALUES ('T2113', false, true, true, NULL, NULL);
INSERT INTO unidades (unidade, pne, presente, adimplente, vaga_sorteada, vagas_escolhidas) VALUES ('T2114', false, true, true, NULL, NULL);
INSERT INTO unidades (unidade, pne, presente, adimplente, vaga_sorteada, vagas_escolhidas) VALUES ('T2121', false, true, true, NULL, NULL);
INSERT INTO unidades (unidade, pne, presente, adimplente, vaga_sorteada, vagas_escolhidas) VALUES ('T2122', false, true, true, NULL, NULL);
INSERT INTO unidades (unidade, pne, presente, adimplente, vaga_sorteada, vagas_escolhidas) VALUES ('T2123', false, true, true, NULL, NULL);
INSERT INTO unidades (unidade, pne, presente, adimplente, vaga_sorteada, vagas_escolhidas) VALUES ('T2124', false, true, true, NULL, NULL);
INSERT INTO unidades (unidade, pne, presente, adimplente, vaga_sorteada, vagas_escolhidas) VALUES ('T2131', false, true, true, NULL, NULL);
INSERT INTO unidades (unidade, pne, presente, adimplente, vaga_sorteada, vagas_escolhidas) VALUES ('T2132', false, true, true, NULL, NULL);
INSERT INTO unidades (unidade, pne, presente, adimplente, vaga_sorteada, vagas_escolhidas) VALUES ('T2133', false, true, true, NULL, NULL);
INSERT INTO unidades (unidade, pne, presente, adimplente, vaga_sorteada, vagas_escolhidas) VALUES ('T2134', false, true, true, NULL, NULL);
INSERT INTO unidades (unidade, pne, presente, adimplente, vaga_sorteada, vagas_escolhidas) VALUES ('T2141', false, true, true, NULL, NULL);
INSERT INTO unidades (unidade, pne, presente, adimplente, vaga_sorteada, vagas_escolhidas) VALUES ('T2142', false, true, true, NULL, NULL);
INSERT INTO unidades (unidade, pne, presente, adimplente, vaga_sorteada, vagas_escolhidas) VALUES ('T2143', false, true, true, NULL, NULL);
INSERT INTO unidades (unidade, pne, presente, adimplente, vaga_sorteada, vagas_escolhidas) VALUES ('T2144', false, true, true, NULL, NULL);
INSERT INTO unidades (unidade, pne, presente, adimplente, vaga_sorteada, vagas_escolhidas) VALUES ('T2151', false, true, true, NULL, NULL);
INSERT INTO unidades (unidade, pne, presente, adimplente, vaga_sorteada, vagas_escolhidas) VALUES ('T2152', false, true, true, NULL, NULL);
INSERT INTO unidades (unidade, pne, presente, adimplente, vaga_sorteada, vagas_escolhidas) VALUES ('T2153', false, true, true, NULL, NULL);
INSERT INTO unidades (unidade, pne, presente, adimplente, vaga_sorteada, vagas_escolhidas) VALUES ('T2154', false, true, true, NULL, NULL);
INSERT INTO unidades (unidade, pne, presente, adimplente, vaga_sorteada, vagas_escolhidas) VALUES ('T2161', false, true, true, NULL, NULL);
INSERT INTO unidades (unidade, pne, presente, adimplente, vaga_sorteada, vagas_escolhidas) VALUES ('T2162', false, true, true, NULL, NULL);
INSERT INTO unidades (unidade, pne, presente, adimplente, vaga_sorteada, vagas_escolhidas) VALUES ('T2163', false, true, true, NULL, NULL);
INSERT INTO unidades (unidade, pne, presente, adimplente, vaga_sorteada, vagas_escolhidas) VALUES ('T2164', false, true, true, NULL, NULL);
INSERT INTO unidades (unidade, pne, presente, adimplente, vaga_sorteada, vagas_escolhidas) VALUES ('T2171', false, true, true, NULL, NULL);
INSERT INTO unidades (unidade, pne, presente, adimplente, vaga_sorteada, vagas_escolhidas) VALUES ('T2172', false, true, true, NULL, NULL);
INSERT INTO unidades (unidade, pne, presente, adimplente, vaga_sorteada, vagas_escolhidas) VALUES ('T2173', false, true, true, NULL, NULL);
INSERT INTO unidades (unidade, pne, presente, adimplente, vaga_sorteada, vagas_escolhidas) VALUES ('T2174', false, true, true, NULL, NULL);
INSERT INTO unidades (unidade, pne, presente, adimplente, vaga_sorteada, vagas_escolhidas) VALUES ('T2181', false, true, true, NULL, NULL);
INSERT INTO unidades (unidade, pne, presente, adimplente, vaga_sorteada, vagas_escolhidas) VALUES ('T2182', false, true, true, NULL, NULL);
INSERT INTO unidades (unidade, pne, presente, adimplente, vaga_sorteada, vagas_escolhidas) VALUES ('T2183', false, true, true, NULL, NULL);
INSERT INTO unidades (unidade, pne, presente, adimplente, vaga_sorteada, vagas_escolhidas) VALUES ('T2184', false, true, true, NULL, NULL);
INSERT INTO unidades (unidade, pne, presente, adimplente, vaga_sorteada, vagas_escolhidas) VALUES ('T2191', false, true, true, NULL, NULL);
INSERT INTO unidades (unidade, pne, presente, adimplente, vaga_sorteada, vagas_escolhidas) VALUES ('T2192', false, true, true, NULL, NULL);
INSERT INTO unidades (unidade, pne, presente, adimplente, vaga_sorteada, vagas_escolhidas) VALUES ('T2193', false, true, true, NULL, NULL);
INSERT INTO unidades (unidade, pne, presente, adimplente, vaga_sorteada, vagas_escolhidas) VALUES ('T2194', false, true, true, NULL, NULL);
INSERT INTO unidades (unidade, pne, presente, adimplente, vaga_sorteada, vagas_escolhidas) VALUES ('T2201', false, true, true, NULL, NULL);
INSERT INTO unidades (unidade, pne, presente, adimplente, vaga_sorteada, vagas_escolhidas) VALUES ('T2202', false, true, true, NULL, NULL);
INSERT INTO unidades (unidade, pne, presente, adimplente, vaga_sorteada, vagas_escolhidas) VALUES ('T2203', false, true, true, NULL, NULL);
INSERT INTO unidades (unidade, pne, presente, adimplente, vaga_sorteada, vagas_escolhidas) VALUES ('T2204', false, true, true, NULL, NULL);
INSERT INTO unidades (unidade, pne, presente, adimplente, vaga_sorteada, vagas_escolhidas) VALUES ('T2211', false, true, true, NULL, NULL);
INSERT INTO unidades (unidade, pne, presente, adimplente, vaga_sorteada, vagas_escolhidas) VALUES ('T2212', false, true, true, NULL, NULL);
INSERT INTO unidades (unidade, pne, presente, adimplente, vaga_sorteada, vagas_escolhidas) VALUES ('T2213', false, true, true, NULL, NULL);
INSERT INTO unidades (unidade, pne, presente, adimplente, vaga_sorteada, vagas_escolhidas) VALUES ('T2214', false, true, true, NULL, NULL);
INSERT INTO unidades (unidade, pne, presente, adimplente, vaga_sorteada, vagas_escolhidas) VALUES ('T2221', false, true, true, NULL, NULL);
INSERT INTO unidades (unidade, pne, presente, adimplente, vaga_sorteada, vagas_escolhidas) VALUES ('T2222', false, true, true, NULL, NULL);
INSERT INTO unidades (unidade, pne, presente, adimplente, vaga_sorteada, vagas_escolhidas) VALUES ('T2223', false, true, true, NULL, NULL);
INSERT INTO unidades (unidade, pne, presente, adimplente, vaga_sorteada, vagas_escolhidas) VALUES ('T2224', false, true, true, NULL, NULL);
INSERT INTO unidades (unidade, pne, presente, adimplente, vaga_sorteada, vagas_escolhidas) VALUES ('T2231', false, true, true, NULL, NULL);
INSERT INTO unidades (unidade, pne, presente, adimplente, vaga_sorteada, vagas_escolhidas) VALUES ('T2232', false, true, true, NULL, NULL);
INSERT INTO unidades (unidade, pne, presente, adimplente, vaga_sorteada, vagas_escolhidas) VALUES ('T2233', false, true, true, NULL, NULL);
INSERT INTO unidades (unidade, pne, presente, adimplente, vaga_sorteada, vagas_escolhidas) VALUES ('T2234', false, true, true, NULL, NULL);
INSERT INTO unidades (unidade, pne, presente, adimplente, vaga_sorteada, vagas_escolhidas) VALUES ('T2241', false, true, true, NULL, NULL);
INSERT INTO unidades (unidade, pne, presente, adimplente, vaga_sorteada, vagas_escolhidas) VALUES ('T2242', false, true, true, NULL, NULL);
INSERT INTO unidades (unidade, pne, presente, adimplente, vaga_sorteada, vagas_escolhidas) VALUES ('T2243', false, true, true, NULL, NULL);
INSERT INTO unidades (unidade, pne, presente, adimplente, vaga_sorteada, vagas_escolhidas) VALUES ('T2244', false, true, true, NULL, NULL);